name: reviewdog

on:
  - pull_request
  - workflow_dispatch

jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: textlint
        uses: Khsmty/action-textlint@91807bd487f2638e5a4db7e02595aed4312958c9
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          textlint_flags: 'data/**'
          package_manager: pnpm
