name: reviewdog

on: [pull_request]

jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: textlint
        uses: Khsmty/action-textlint@6d058a525e151db1499ec4fd234f3463f0553567
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          textlint_flags: 'data/**'
          package_manager: pnpm
